# Numpy

## To check the numpy version in the system

In [1]:
import numpy as np
np.__version__

'1.15.1'

###  Single Dimensional Array

In [6]:
import numpy as np
a=[1,56,89]
np.array(a)

array([ 1, 56, 89])

### Two Dimensional Array(This is generally used)

In [15]:
import numpy as np
b=[5,4,3], [1,2,3]
np.array(b)


array([[5, 4, 3],
       [1, 2, 3]])

In [7]:
import numpy as np
b=[5,4,3], [1,2,3]
b1=np.array(b)            #---> np.array is used to convert python list to array
print(b1)                 #---> print b1 values
print(b1+10)              #--->You could perform mathematical operations like additions, subtraction, division and multiplication on an array. The syntax is the array name followed by the operation (+.-,*,/) followed by the operand 

[[5 4 3]
 [1 2 3]]
[[15 14 13]
 [11 12 13]]


# Shape of an Array

### You can check the shape of the array with the object shape preceded by the name of the array. In the same way, you can check the type with dtypes 

In [18]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a.shape)  #---------> specifies the shape of the array id it is 2x2 or 3x3 or 1x1 matrcix
print(a.size)   #----------> count of the each element present in the array
print(a.dtype)

(2, 3)
6
int32


## Three Dimensional Array

In [1]:
import numpy as np
a1=np.array([[[1,2,3],[2,4,5]]])
print(a1.shape)

(1, 2, 3)


# numpy.zeros() and numpy.ones() in Python 


What is np.zeros and np.ones?
You can create a matrix full of zeroes or ones using np.zeros and np.one commands respectively. It can be used when you initialized the weights during the first iteration in TensorFlow and other statistic tasks. 

# # The syntax is 
### Numpy Zero 
numpy.zeros(shape, dtype=float, order='C')
### Numpy Once 
numpy.ones(shape, dtype=float, order='C')

#### Here, 
Shape: is the shape of the array 
Dtype: is the datatype. It is optional. The default value is float64
Order: Default is C which is an essential row style. 

#### To print 2x2 matrix with Zeros and ones

In [22]:
import numpy as np
a2=np.array([[1,4,5],[3,6,7]])
print(a2)
np.zeros((2,2),dtype=int,order='C')

[[1 4 5]
 [3 6 7]]


array([[0, 0],
       [0, 0]])

#### To print 2x2 matrix with ones and with datatype in output, type np.dtype=int16

In [30]:
import numpy as np
np.ones([2,2], dtype=np.int16)

array([[1, 1],
       [1, 1]], dtype=int16)

#### To Reshape a given numpy variable. you can reshape only if the size are same. 

In [33]:
import numpy as np
a1=np.array([[2,4,5],[5,9,4]])
print(a1)
a1.reshape(3,2)

[[2 4 5]
 [5 9 4]]


array([[2, 4],
       [5, 5],
       [9, 4]])

#### If we try to give the reshape value as 3,5 which should have 15 elements in array it displays an error. it should only have the size of the array so that we can reshape

In [34]:
import numpy as np
a1=np.array([[2,4,5],[5,9,4]])
print(a1)
a1.reshape(3,5)

[[2 4 5]
 [5 9 4]]


ValueError: cannot reshape array of size 6 into shape (3,5)

# Flatten()

## When you deal with some neural network like convnet, you need to flatten the array. You can use flatten(). The syntax is 

### numpy.flatten(Order='C')

In [35]:
import numpy as np
a1=np.array([[2,4,5],[5,9,4]])
print(a1)
a1.flatten()

[[2 4 5]
 [5 9 4]]


array([2, 4, 5, 5, 9, 4])

# numpy.hstack() and numpy.vstack() in Python with Example 

##  numpy.hstack() --> To append horizontally

In [5]:
import numpy as np
a1=np.array([[1,2,3],[4,5,6]])
b1=np.array([[3,4,5],[9,8,5]])
print(np.hstack((a1,b1)))         #-------------> always give ((var1,var2))

[[1 2 3 3 4 5]
 [4 5 6 9 8 5]]


## numpy.vstack() ---> To append Vertically

In [7]:
import numpy as np
a1=np.array([[5,2,3],[4,5,6]])
b1=np.array([[3,90,5],[9,8,50]])
print(np.vstack((b1,a1)))   #-------------> always give ((var1,var2))

[[ 3 90  5]
 [ 9  8 50]
 [ 5  2  3]
 [ 4  5  6]]


# Generate Random Numbers
## To generate random numbers for Gaussian distribution use 
### numpy.random.normal(loc, scale, size) 
### Here 
#### Loc: the mean. The center of distribution 
#### scale: standard deviation. 
#### Size: number of returns

### Test Leaf Assignment

###  1.np.eye and np.identity

In [19]:
import numpy as np
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [17]:
import numpy as np
np.identity(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [13]:
import numpy as np
a= np.array([[1,0,0],
             [0,1,0],
             [0,0,1]])
a

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

# Telecom Churn Dataset

### To find the number of rows and columns we use shape. id we use shape[0] it will return number of row. when no value is declared it will print both rows and columns

In [269]:
import numpy as np
t1=np.genfromtxt('C:\\Users\\320300\\Desktop\\Telecom Customer Churn.csv',dtype=str,delimiter=',',skip_header=1,usecols=None)
t1.shape

(3333, 22)

### Find the count of VMail plan holders(yes) who churned? 

In [276]:
import numpy as np
t1=np.genfromtxt('C:\\Users\\320300\\Desktop\\Telecom Customer Churn.csv',dtype='object',delimiter=',',names=True)
t2=t1[(t1['VMail_Plan']==b'yes') & (t1['Churn']==b'True.')]['VMail_Plan'].size
t2

80

### Find the Average international plan holders in the churning ratio?

In [275]:
import numpy as np

t1=np.genfromtxt('C:\\Users\\320300\\Desktop\\Telecom Customer Churn.csv',dtype='object',delimiter=',',names=True)

t11=t1.shape[0]        # To print the row count, we use shape[0]

#print(t1.dtype.names)  # To find the column name of the givwen data set

t2=t1[(t1['Intl_Plan']==b'yes') &(t1['Churn']==b'True.')]

t15= t2.shape[0]

avg1= t15/t11

print(avg1)


0.0411041104110411


### Find the least area-codes that have churned?

In [221]:
import numpy as np
t1=np.genfromtxt('C:\\Users\\320300\\Desktop\\Telecom Customer Churn.csv',dtype='object',delimiter=',',names=True)
print(t1.dtype.names)  # To find the column name of the givwen data set
t2=t1[(t1['Churn']==b'True.')]['Area_Code'].min()
t2

('Customer', 'State', 'Account_Length', 'Area_Code', 'Phone', 'Intl_Plan', 'VMail_Plan', 'VMail_Message', 'Day_Mins', 'Day_Calls', 'Day_Charge', 'Eve_Mins', 'Eve_Calls', 'Eve_Charge', 'Night_Mins', 'Night_Calls', 'Night_Charge', 'Intl_Mins', 'Intl_Calls', 'Intl_Charge', 'CustServ_Calls', 'Churn')


b'408'

### #4 A Caller making more nightly calls churn than the evening/day calls?


In [2]:
import numpy as np
t11=np.genfromtxt('C:\\Users\\abc\\Desktop\\Telecom.csv',dtype='object',delimiter=',',names=True)
print(t11.dtype.names)
print(t11)

('Customer', 'State', 'Account_Length', 'Area_Code', 'Phone', 'Intl_Plan', 'VMail_Plan', 'VMail_Message', 'Day_Mins', 'Day_Calls', 'Day_Charge', 'Eve_Mins', 'Eve_Calls', 'Eve_Charge', 'Night_Mins', 'Night_Calls', 'Night_Charge', 'Intl_Mins', 'Intl_Calls', 'Intl_Charge', 'CustServ_Calls', 'Churn')
[(b'A1001', b'KS', b'128', b'415', b'382-4657', b'no', b'yes', b'25', b'265.1', b'110', b'45.07', b'197.4', b'99', b'16.78', b'244.7', b'91', b'11.01', b'10', b'3', b'2.7', b'1', b'False.')
 (b'A1002', b'OH', b'107', b'415', b'371-7191', b'no', b'yes', b'26', b'161.6', b'123', b'27.47', b'195.5', b'103', b'16.62', b'254.4', b'103', b'11.45', b'13.7', b'3', b'3.7', b'1', b'False.')
 (b'A1003', b'NJ', b'137', b'415', b'358-1921', b'no', b'no', b'0', b'243.4', b'114', b'41.38', b'121.2', b'110', b'10.3', b'162.6', b'104', b'7.32', b'12.2', b'5', b'3.29', b'0', b'False.')
 ...
 (b'A4331', b'RI', b'28', b'510', b'328-8230', b'no', b'no', b'0', b'180.8', b'109', b'30.74', b'288.8', b'58', b'24.55', 

In [36]:
import numpy as np
t11=np.genfromtxt('C:\\Users\\abc\\Desktop\\Telecom.csv',dtype='object',delimiter=',',names=True)
t2=t11[(t11['Churn']==b'True.')]['Night_Calls'].size
t3=t11[(t11['Churn']==b'True.')]['Day_Calls'].size
t4=t11[(t11['Churn']==b'True.')]['Eve_Calls'].size
np.greater(t2,t3)& np.greater(t3,t4)

False

### #4 B  The average calls made in the evening are higher than day?


In [2]:
import numpy as np
t11=np.genfromtxt('C:\\Users\\abc\\Desktop\\Telecom.csv',dtype='int',delimiter=',',names=True)
t5=t11['Eve_Calls']  
t6=t11['Day_Calls']
print(np.average(t5))
print(np.average(t6))
np.average(t5)>np.average(t6)

100.11431143114311
100.43564356435644


False

### #4 C The person who does less customer service call does not churn?


In [7]:
import numpy as np
t11=np.genfromtxt('C:\\Users\\abc\\Desktop\\Telecom.csv',dtype='object',delimiter=',',names=True)
t7=t11[(t11['Churn']==b'True.')&(t11['CustServ_Calls']==b'0')].size   # less calls = 0, churn= true
t8=t11[(t11['Churn']==b'False.')&(t11['CustServ_Calls']==b'0')].size  # less calls = 0, churn=false
print(t7)
print(t8)
np.greater(t8,t7)

92
605


True

### What happens when we use operator on differnt shapes/ Ans. It will throw an exception. 
### Below is the example

In [6]:
import numpy as np
a=np.zeros(6)
b=np.arange(0,10,2)
print(a)
print(b)
c=a+b
print(c[4])

[0. 0. 0. 0. 0. 0.]
[0 2 4 6 8]


ValueError: operands could not be broadcast together with shapes (6,) (5,) 