# Numpy

## To check the numpy version in the system

In [1]:
import numpy as np
np.__version__

'1.15.1'

###  Single Dimensional Array

In [6]:
import numpy as np
a=[1,56,89]
np.array(a)

array([ 1, 56, 89])

### Two Dimensional Array(This is generally used)

In [15]:
import numpy as np
b=[5,4,3], [1,2,3]
np.array(b)


array([[5, 4, 3],
       [1, 2, 3]])

In [7]:
import numpy as np
b=[5,4,3], [1,2,3]
b1=np.array(b)            #---> np.array is used to convert python list to array
print(b1)                 #---> print b1 values
print(b1+10)              #--->You could perform mathematical operations like additions, subtraction, division and multiplication on an array. The syntax is the array name followed by the operation (+.-,*,/) followed by the operand 

[[5 4 3]
 [1 2 3]]
[[15 14 13]
 [11 12 13]]


# Shape of an Array

### You can check the shape of the array with the object shape preceded by the name of the array. In the same way, you can check the type with dtypes 

In [18]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a.shape)  #---------> specifies the shape of the array id it is 2x2 or 3x3 or 1x1 matrcix
print(a.size)   #----------> count of the each element present in the array
print(a.dtype)

(2, 3)
6
int32


## Three Dimensional Array

In [1]:
import numpy as np
a1=np.array([[[1,2,3],[2,4,5]]])
print(a1.shape)

(1, 2, 3)


# numpy.zeros() and numpy.ones() in Python 


What is np.zeros and np.ones?
You can create a matrix full of zeroes or ones using np.zeros and np.one commands respectively. It can be used when you initialized the weights during the first iteration in TensorFlow and other statistic tasks. 

# # The syntax is 
### Numpy Zero 
numpy.zeros(shape, dtype=float, order='C')
### Numpy Once 
numpy.ones(shape, dtype=float, order='C')

#### Here, 
Shape: is the shape of the array 
Dtype: is the datatype. It is optional. The default value is float64
Order: Default is C which is an essential row style. 

#### To print 2x2 matrix with Zeros and ones

In [22]:
import numpy as np
a2=np.array([[1,4,5],[3,6,7]])
print(a2)
np.zeros((2,2),dtype=int,order='C')

[[1 4 5]
 [3 6 7]]


array([[0, 0],
       [0, 0]])

#### To print 2x2 matrix with ones and with datatype in output, type np.dtype=int16

In [30]:
import numpy as np
np.ones([2,2], dtype=np.int16)

array([[1, 1],
       [1, 1]], dtype=int16)

#### To Reshape a given numpy variable. you can reshape only if the size are same. 

In [33]:
import numpy as np
a1=np.array([[2,4,5],[5,9,4]])
print(a1)
a1.reshape(3,2)

[[2 4 5]
 [5 9 4]]


array([[2, 4],
       [5, 5],
       [9, 4]])

#### If we try to give the reshape value as 3,5 which should have 15 elements in array it displays an error. it should only have the size of the array so that we can reshape

In [34]:
import numpy as np
a1=np.array([[2,4,5],[5,9,4]])
print(a1)
a1.reshape(3,5)

[[2 4 5]
 [5 9 4]]


ValueError: cannot reshape array of size 6 into shape (3,5)

# Flatten()

## When you deal with some neural network like convnet, you need to flatten the array. You can use flatten(). The syntax is 

### numpy.flatten(Order='C')

In [35]:
import numpy as np
a1=np.array([[2,4,5],[5,9,4]])
print(a1)
a1.flatten()

[[2 4 5]
 [5 9 4]]


array([2, 4, 5, 5, 9, 4])

# numpy.hstack() and numpy.vstack() in Python with Example 

##  numpy.hstack() --> To append horizontally

In [5]:
import numpy as np
a1=np.array([[1,2,3],[4,5,6]])
b1=np.array([[3,4,5],[9,8,5]])
print(np.hstack((a1,b1)))         #-------------> always give ((var1,var2))

[[1 2 3 3 4 5]
 [4 5 6 9 8 5]]


## numpy.vstack() ---> To append Vertically

In [7]:
import numpy as np
a1=np.array([[5,2,3],[4,5,6]])
b1=np.array([[3,90,5],[9,8,50]])
print(np.vstack((b1,a1)))   #-------------> always give ((var1,var2))

[[ 3 90  5]
 [ 9  8 50]
 [ 5  2  3]
 [ 4  5  6]]


# Generate Random Numbers
## To generate random numbers for Gaussian distribution use 
### numpy.random.normal(loc, scale, size) 
### Here 
#### Loc: the mean. The center of distribution 
#### scale: standard deviation. 
#### Size: number of returns

### Test Leaf Assignment

###  1.np.eye and np.identity

In [19]:
import numpy as np
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [17]:
import numpy as np
np.identity(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [13]:
import numpy as np
a= np.array([[1,0,0],
             [0,1,0],
             [0,0,1]])
a

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

# Telecom Churn Dataset

### To find the number of rows and columns we use shape. id we use shape[0] it will return number of row. when no value is declared it will print both rows and columns

In [269]:
import numpy as np
t1=np.genfromtxt('C:\\Users\\320300\\Desktop\\Telecom Customer Churn.csv',dtype=str,delimiter=',',skip_header=1,usecols=None)
t1.shape

(3333, 22)

### Find the count of VMail plan holders(yes) who churned? 

In [276]:
import numpy as np
t1=np.genfromtxt('C:\\Users\\320300\\Desktop\\Telecom Customer Churn.csv',dtype='object',delimiter=',',names=True)
t2=t1[(t1['VMail_Plan']==b'yes') & (t1['Churn']==b'True.')]['VMail_Plan'].size
t2

80

### Find the Average international plan holders in the churning ratio?

In [64]:
import numpy as np

t1=np.genfromtxt('C:\\Users\\abc\\Desktop\\Telecom.csv',dtype='object',delimiter=',',names=True)

t11=t1.shape[0]        # To print the row count, we use shape[0]

#print(t11)

#print(t1.dtype.names)  # To find the column name of the givwen data set

t2=t1[(t1['Intl_Plan']==b'yes') &(t1['Churn']==b'True.')]

t15= t2.shape[0]

avg1= t15/t11

print(avg1)


3333
0.0411041104110411


### Find the least area-codes that have churned?

In [221]:
import numpy as np
t1=np.genfromtxt('C:\\Users\\320300\\Desktop\\Telecom Customer Churn.csv',dtype='object',delimiter=',',names=True)
print(t1.dtype.names)  # To find the column name of the givwen data set
t2=t1[(t1['Churn']==b'True.')]['Area_Code'].min()
t2

('Customer', 'State', 'Account_Length', 'Area_Code', 'Phone', 'Intl_Plan', 'VMail_Plan', 'VMail_Message', 'Day_Mins', 'Day_Calls', 'Day_Charge', 'Eve_Mins', 'Eve_Calls', 'Eve_Charge', 'Night_Mins', 'Night_Calls', 'Night_Charge', 'Intl_Mins', 'Intl_Calls', 'Intl_Charge', 'CustServ_Calls', 'Churn')


b'408'

### #4 A Caller making more nightly calls churn than the evening/day calls?


In [2]:
import numpy as np
t11=np.genfromtxt('C:\\Users\\abc\\Desktop\\Telecom.csv',dtype='object',delimiter=',',names=True)
print(t11.dtype.names)
print(t11)

('Customer', 'State', 'Account_Length', 'Area_Code', 'Phone', 'Intl_Plan', 'VMail_Plan', 'VMail_Message', 'Day_Mins', 'Day_Calls', 'Day_Charge', 'Eve_Mins', 'Eve_Calls', 'Eve_Charge', 'Night_Mins', 'Night_Calls', 'Night_Charge', 'Intl_Mins', 'Intl_Calls', 'Intl_Charge', 'CustServ_Calls', 'Churn')
[(b'A1001', b'KS', b'128', b'415', b'382-4657', b'no', b'yes', b'25', b'265.1', b'110', b'45.07', b'197.4', b'99', b'16.78', b'244.7', b'91', b'11.01', b'10', b'3', b'2.7', b'1', b'False.')
 (b'A1002', b'OH', b'107', b'415', b'371-7191', b'no', b'yes', b'26', b'161.6', b'123', b'27.47', b'195.5', b'103', b'16.62', b'254.4', b'103', b'11.45', b'13.7', b'3', b'3.7', b'1', b'False.')
 (b'A1003', b'NJ', b'137', b'415', b'358-1921', b'no', b'no', b'0', b'243.4', b'114', b'41.38', b'121.2', b'110', b'10.3', b'162.6', b'104', b'7.32', b'12.2', b'5', b'3.29', b'0', b'False.')
 ...
 (b'A4331', b'RI', b'28', b'510', b'328-8230', b'no', b'no', b'0', b'180.8', b'109', b'30.74', b'288.8', b'58', b'24.55', 

In [36]:
import numpy as np
t11=np.genfromtxt('C:\\Users\\abc\\Desktop\\Telecom.csv',dtype='object',delimiter=',',names=True)
t2=t11[(t11['Churn']==b'True.')]['Night_Calls'].size
t3=t11[(t11['Churn']==b'True.')]['Day_Calls'].size
t4=t11[(t11['Churn']==b'True.')]['Eve_Calls'].size
np.greater(t2,t3)& np.greater(t3,t4)

False

### #4 B  The average calls made in the evening are higher than day?


In [2]:
import numpy as np
t11=np.genfromtxt('C:\\Users\\abc\\Desktop\\Telecom.csv',dtype='int',delimiter=',',names=True)
t5=t11['Eve_Calls']  
t6=t11['Day_Calls']
print(np.average(t5))
print(np.average(t6))
np.average(t5)>np.average(t6)

100.11431143114311
100.43564356435644


False

### #4 C The person who does less customer service call does not churn?


In [7]:
import numpy as np
t11=np.genfromtxt('C:\\Users\\abc\\Desktop\\Telecom.csv',dtype='object',delimiter=',',names=True)
t7=t11[(t11['Churn']==b'True.')&(t11['CustServ_Calls']==b'0')].size   # less calls = 0, churn= true
t8=t11[(t11['Churn']==b'False.')&(t11['CustServ_Calls']==b'0')].size  # less calls = 0, churn=false
print(t7)
print(t8)
np.greater(t8,t7)

92
605


True

### What happens when we use operator on differnt shapes/ Ans. It will throw an exception. 
### Below is the example

In [6]:
import numpy as np
a=np.zeros(6)
b=np.arange(0,10,2)
print(a)
print(b)
c=a+b
print(c[4])

[0. 0. 0. 0. 0. 0.]
[0 2 4 6 8]


ValueError: operands could not be broadcast together with shapes (6,) (5,) 

In [35]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [81]:
data=pd.read_csv('C:\\Users\\abc\\Desktop\\Telecom.csv')
data.shape

(3333, 22)

In [93]:
data.columns

Index(['Customer', 'State', 'Account Length', 'Area Code', 'Phone',
       'Int'l Plan', 'VMail Plan', 'VMail Message', 'Day Mins', 'Day Calls',
       'Day Charge', 'Eve Mins', 'Eve Calls', 'Eve Charge', 'Night Mins',
       'Night Calls', 'Night Charge', 'Intl Mins', 'Intl Calls', 'Intl Charge',
       'CustServ Calls', 'Churn?'],
      dtype='object')

In [96]:
data.rename(columns={'Churn?':'Churn'},inplace=True)

In [98]:
data.head(10)

Customer State  Account Length  Area Code     Phone Int'l Plan VMail Plan  \
0    A1001    KS             128        415  382-4657         no        yes   
1    A1002    OH             107        415  371-7191         no        yes   
2    A1003    NJ             137        415  358-1921         no         no   
3    A1004    OH              84        408  375-9999        yes         no   
4    A1005    OK              75        415  330-6626        yes         no   
5    A1006    AL             118        510  391-8027        yes         no   
6    A1007    MA             121        510  355-9993         no        yes   
7    A1008    MO             147        415  329-9001        yes         no   
8    A1009    LA             117        408  335-4719         no         no   
9    A1010    WV             141        415  330-8173        yes        yes   

   VMail Message  Day Mins  Day Calls  ...  Eve Calls  Eve Charge  Night Mins  \
0             25     265.1        110  ...         99       16.78       244.7   
1             26     161.6        123  ...        103       16.62       254.4   
2              0     243.4        114  ...        110       10.30       162.6   
3              0     299.4         71  ...         88        5.26       196.9   
4              0     166.7        113  ...        122       12.61       186.9   
5              0     223.4         98  ...        101       18.75       203.9   
6             24     218.2         88  ...        108       29.62       212.6   
7              0     157.0         79  ...         94        8.76       211.8   
8              0     184.5         97  ...         80       29.89       215.8   
9             37     258.6         84  ...        111       18.87       326.4   

   Night Calls  Night Charge  Intl Mins  Intl Calls  Intl Charge  \
0           91         11.01       10.0           3         2.70   
1          103         11.45       13.7           3         3.70   
2          104          7.32       12.2           5         3.29   
3           89          8.86        6.6           7         1.78   
4          121          8.41       10.1           3         2.73   
5          118          9.18        6.3           6         1.70   
6          118          9.57        7.5           7         2.03   
7           96          9.53        7.1           6         1.92   
8           90          9.71        8.7           4         2.35   
9           97         14.69       11.2           5         3.02   

   CustServ Calls  Churn  
0               1    NaN  
1               1    NaN  
2               0    NaN  
3               2    NaN  
4               3    NaN  
5               0    NaN  
6               3    NaN  
7               0    NaN  
8               1    NaN  
9               0    NaN  

[10 rows x 22 columns]

In [44]:
data.isnull().values.any()

False

In [99]:
data.describe()

Account Length    Area Code  VMail Message     Day Mins    Day Calls  \
count     3333.000000  3333.000000    3333.000000  3333.000000  3333.000000   
mean       101.064806   437.182418       8.099010   179.775098   100.435644   
std         39.822106    42.371290      13.688365    54.467389    20.069084   
min          1.000000   408.000000       0.000000     0.000000     0.000000   
25%         74.000000   408.000000       0.000000   143.700000    87.000000   
50%        101.000000   415.000000       0.000000   179.400000   101.000000   
75%        127.000000   510.000000      20.000000   216.400000   114.000000   
max        243.000000   510.000000      51.000000   350.800000   165.000000   

        Day Charge     Eve Mins    Eve Calls   Eve Charge   Night Mins  \
count  3333.000000  3333.000000  3333.000000  3333.000000  3333.000000   
mean     30.562307   200.980348   100.114311    17.083540   200.872037   
std       9.259435    50.713844    19.922625     4.310668    50.573847   
min       0.000000     0.000000     0.000000     0.000000    23.200000   
25%      24.430000   166.600000    87.000000    14.160000   167.000000   
50%      30.500000   201.400000   100.000000    17.120000   201.200000   
75%      36.790000   235.300000   114.000000    20.000000   235.300000   
max      59.640000   363.700000   170.000000    30.910000   395.000000   

       Night Calls  Night Charge    Intl Mins   Intl Calls  Intl Charge  \
count  3333.000000   3333.000000  3333.000000  3333.000000  3333.000000   
mean    100.107711      9.039325    10.237294     4.479448     2.764581   
std      19.568609      2.275873     2.791840     2.461214     0.753773   
min      33.000000      1.040000     0.000000     0.000000     0.000000   
25%      87.000000      7.520000     8.500000     3.000000     2.300000   
50%     100.000000      9.050000    10.300000     4.000000     2.780000   
75%     113.000000     10.590000    12.100000     6.000000     3.270000   
max     175.000000     17.770000    20.000000    20.000000     5.400000   

       CustServ Calls  Churn  
count     3333.000000    0.0  
mean         1.562856    NaN  
std          1.315491    NaN  
min          0.000000    NaN  
25%          1.000000    NaN  
50%          1.000000    NaN  
75%          2.000000    NaN  
max          9.000000    NaN

In [104]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3333 entries, 0 to 3332
Data columns (total 22 columns):
Customer          3333 non-null object
State             3333 non-null object
Account Length    3333 non-null int64
Area Code         3333 non-null int64
Phone             3333 non-null object
Int'l Plan        3333 non-null object
VMail Plan        3333 non-null object
VMail Message     3333 non-null int64
Day Mins          3333 non-null float64
Day Calls         3333 non-null int64
Day Charge        3333 non-null float64
Eve Mins          3333 non-null float64
Eve Calls         3333 non-null int64
Eve Charge        3333 non-null float64
Night Mins        3333 non-null float64
Night Calls       3333 non-null int64
Night Charge      3333 non-null float64
Intl Mins         3333 non-null float64
Intl Calls        3333 non-null int64
Intl Charge       3333 non-null float64
CustServ Calls    3333 non-null int64
Churn             0 non-null float64
dtypes: float64(9), int64(8), object(

In [277]:
import seaborn as sns
corrmat=data.corr()
top_corr_features=corrmat.index
plt.figure(figsize=(25,25))
g=sns.heatmap(data[top_corr_features].corr(),annot=True,cmap="RdYlGn")

NameError: name 'data' is not defined

In [101]:
data.corr()

Account Length  Area Code  VMail Message  Day Mins  Day Calls  \
Account Length        1.000000  -0.012463      -0.004628  0.006216   0.038470   
Area Code            -0.012463   1.000000      -0.001994 -0.008264  -0.009646   
VMail Message        -0.004628  -0.001994       1.000000  0.000778  -0.009548   
Day Mins              0.006216  -0.008264       0.000778  1.000000   0.006750   
Day Calls             0.038470  -0.009646      -0.009548  0.006750   1.000000   
Day Charge            0.006214  -0.008264       0.000776  1.000000   0.006753   
Eve Mins             -0.006757   0.003580       0.017562  0.007043  -0.021451   
Eve Calls             0.019260  -0.011886      -0.005864  0.015769   0.006462   
Eve Charge           -0.006745   0.003607       0.017578  0.007029  -0.021449   
Night Mins           -0.008955  -0.005825       0.007681  0.004323   0.022938   
Night Calls          -0.013176   0.016522       0.007123  0.022972  -0.019557   
Night Charge         -0.008960  -0.005845       0.007663  0.004300   0.022927   
Intl Mins             0.009514  -0.018288       0.002856 -0.010155   0.021565   
Intl Calls            0.020661  -0.024179       0.013957  0.008033   0.004574   
Intl Charge           0.009546  -0.018395       0.002884 -0.010092   0.021666   
CustServ Calls       -0.003796   0.027572      -0.013263 -0.013423  -0.018942   
Churn                      NaN        NaN            NaN       NaN        NaN   

                Day Charge  Eve Mins  Eve Calls  Eve Charge  Night Mins  \
Account Length    0.006214 -0.006757   0.019260   -0.006745   -0.008955   
Area Code        -0.008264  0.003580  -0.011886    0.003607   -0.005825   
VMail Message     0.000776  0.017562  -0.005864    0.017578    0.007681   
Day Mins          1.000000  0.007043   0.015769    0.007029    0.004323   
Day Calls         0.006753 -0.021451   0.006462   -0.021449    0.022938   
Day Charge        1.000000  0.007050   0.015769    0.007036    0.004324   
Eve Mins          0.007050  1.000000  -0.011430    1.000000   -0.012584   
Eve Calls         0.015769 -0.011430   1.000000   -0.011423   -0.002093   
Eve Charge        0.007036  1.000000  -0.011423    1.000000   -0.012592   
Night Mins        0.004324 -0.012584  -0.002093   -0.012592    1.000000   
Night Calls       0.022972  0.007586   0.007710    0.007596    0.011204   
Night Charge      0.004301 -0.012593  -0.002056   -0.012601    0.999999   
Intl Mins        -0.010157 -0.011035   0.008703   -0.011043   -0.015207   
Intl Calls        0.008032  0.002541   0.017434    0.002541   -0.012353   
Intl Charge      -0.010094 -0.011067   0.008674   -0.011074   -0.015180   
CustServ Calls   -0.013427 -0.012985   0.002423   -0.012987   -0.009288   
Churn                  NaN       NaN        NaN         NaN         NaN   

                Night Calls  Night Charge  Intl Mins  Intl Calls  Intl Charge  \
Account Length    -0.013176     -0.008960   0.009514    0.020661     0.009546   
Area Code          0.016522     -0.005845  -0.018288   -0.024179    -0.018395   
VMail Message      0.007123      0.007663   0.002856    0.013957     0.002884   
Day Mins           0.022972      0.004300  -0.010155    0.008033    -0.010092   
Day Calls         -0.019557      0.022927   0.021565    0.004574     0.021666   
Day Charge         0.022972      0.004301  -0.010157    0.008032    -0.010094   
Eve Mins           0.007586     -0.012593  -0.011035    0.002541    -0.011067   
Eve Calls          0.007710     -0.002056   0.008703    0.017434     0.008674   
Eve Charge         0.007596     -0.012601  -0.011043    0.002541    -0.011074   
Night Mins         0.011204      0.999999  -0.015207   -0.012353    -0.015180   
Night Calls        1.000000      0.011188  -0.013605    0.000305    -0.013630   
Night Charge       0.011188      1.000000  -0.015214   -0.012329    -0.015186   
Intl Mins         -0.013605     -0.015214   1.000000    0.032304     0.999993   
Intl Calls         0.000305     -0.012329   0.032304    1.000000     0.0